# Generated by Django 3.0.2 on 2020-02-11 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alldjecipes', '0004_auto_20200115_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chefuser',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='chefuser',
            name='lastname',
        ),
    ]
