# Generated by Django 3.0.2 on 2020-02-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alldjecipes', '0005_auto_20200211_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='vegan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='vegitarian',
            field=models.BooleanField(default=False),
        ),
    ]
